// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSJOnL_kjIHZJtMJzxLmp0RrJ3qgZ2zA',
    appId: '1:713808133886:web:89e33b051d3dc215142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    authDomain: 'clubindia-rewards.firebaseapp.com',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    measurementId: 'G-THGLRY9KTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPXwkF6_CIVSYhWZ8iUgVrC-BWmnctiQ',
    appId: '1:713808133886:android:81da8db49d4d163c142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRYzkjSySIfqODE6S1WMSp0ZxAbIFMYY',
    appId: '1:713808133886:ios:1bd3b2aa9f4ae4ac142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    iosBundleId: 'com.example.premiumMApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvRYzkjSySIfqODE6S1WMSp0ZxAbIFMYY',
    appId: '1:713808133886:ios:1bd3b2aa9f4ae4ac142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    iosBundleId: 'com.example.premiumMApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlSJOnL_kjIHZJtMJzxLmp0RrJ3qgZ2zA',
    appId: '1:713808133886:web:f9e11e97837b7217142faf',
    messagingSenderId: '713808133886',
    projectId: 'clubindia-rewards',
    authDomain: 'clubindia-rewards.firebaseapp.com',
    storageBucket: 'clubindia-rewards.firebasestorage.app',
    measurementId: 'G-JG4T6XD5JJ',
  );

}